<?php

namespace SourcingIt\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JobTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobTypeRepository extends EntityRepository
{
}
