sourcing_it_site_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SourcingItSiteBundle:Default:index }

sourcing_it_site_dashboard:
    pattern:  /dashboard
    defaults: { _controller: SourcingItSiteBundle:Default:dashboard }
    
SourcingItSiteBundle_job:
    resource: "@SourcingItSiteBundle/Resources/config/routing/job.yml"
    prefix:   /job